### ISSUE TITLE
Running sctx on two samples from the same patient

### ISSUE THREAD

**Issue by DLuong79** [GWW/sctx#3]
I have a group of patients who donated both PBMC and GI samples, and I want to distinguish between donor and recipient cells while also preserving information about each cell's original tissue type. The problem is that for each patient, _the PBMC or GI data by itself isn't big enough for sctx to detect a second genotype_; I have to combine them. Because each tissue sample was run separately, this means that there will almost certainly be barcode overlap. As far as I'm aware, scsnv/sctx doesn't seem to have a way to properly label duplicate barcodes that come from different tissues. 
Ideally, I want to run scsnv on the PBMC and GI data separately, then run sctx on the combined sample while preserving information about the tissue of origin. Even if they are from completely different runs, I'm hoping that sctx can identify donor/recipient genotypes because both samples come from the same patient.

**Comment by GWW** [comment]
I will look into adding a function to scTX that will let you merge multiple SNV calls together.  The unlikely event of barcode overlap shouldn't be an issue this way.  However, I will not be able to get to it until later this week or next week.

**Comment by GWW** [comment]
I think the easiest way to properly combine two samples involves  using the `sctx` command I developed that mixes two samples.   This will ensure that no SNVs are lost if they are present in one sample versus the other. It also eliminates any issues with barcode overlap.

This is documented in the README for sctx but I will summarize what you need to do below:

It requires an barcode_map.txt file with the following format (two columns separated by a tab).

```
name    barcodes
LUNG_1842       0:CGATGGCAGTTATCGC
LUNG_1775       0:TGGCGCATCAGGCGAA
LUNG_1081       0:ACACCGGAGCTGCAAG
PBMC_1023       1:CTCTGGTAGGAGTAGA
```

The first column is the output barcode in the pileup data.  So for example, if you were to combine two datasets you could create a column such as PBMC_{barcode}. 

The second column is the file index (0 for the first file), (1 for the second file).  

You can use:

```
scsnv mixture -a 0 -i scsnv_index_path_prefix -r genome.fa -o mixture/pileup -m barcode_map.txt --l V3 -t 4 <sample 0_collapsed>.bam ><sample 1_collapsed>.bam
```
Note: It is critical that the barcode with the `0` prefix in the map file is the first bam file specified and the `1` prefix is the second. Also, make sure to change the `-l V3` parameter to your library type.
