### ISSUE TITLE
Mixing more than two samples together

### ISSUE THREAD

**Issue by DLuong79** [GWW/sctx#5]
The example for scsnv shows that two samples can be mixed together, but what about three? Is there an upper limit?

**Comment by GWW** [comment]
I wrote it to work with more than one genotype but I have not tested it nor do I have time to support it.  You could try it and see if it works. scTX will not work with more than one genotype.  You would need to look at other tools such as Vireo.

**Comment by DLuong79** [comment]
I don't mean genotype, I mean sample count. I have transplant patients that provided up to three samples each. There should only be two genotypes present (the cells from the donor and the cells from the recipient).

**Comment by GWW** [comment]
I answered that question in my previous comment.  To elaborate, I wrote it to allow mixing as many samples as you want.  I have not tested it with more than 2 and I do not have the time to support mixing more than 2.  If it works great, if not, you will have to find your own solution.
